name: "JwInf 2018 Runde 1"
participation_start: "2009-01-01T12:00:00+01:00"
participation_end: "2009-01-01T12:00:00+01:00"
duration_minutes: 45
public_listing: true

tasks:
  "Aufgabe 1": "blub"
  "Aufgabe 2": ["task2a", "task2b", "task3"]
  "Aufgabe 3":
    "blub/": {stars: 1}
    "blub/index.html": {stars: 3}
    "task3": {stars: 5}


